[package]
name = "problem-of-the-three-bodies"
version = "0.1.0"
edition = "2021"

[dependencies]
image = {version = "0.25.1"}
thiserror = "1.0.58"
clap = {version = "4.5.4", features = ["derive"]}
nalgebra = "0.32.5"
exr = "1.72.0"
